### ISSUE TITLE
Migrate all casks from `appcast` to `livecheck` & review existing `livecheck` blocks

### ISSUE THREAD

**Issue by p-linnane** [Homebrew/homebrew-cask-versions#14993]
### Description of issue

A large number of casks in `homebrew-cask-versions` are still using `appcast` instead of `livecheck`. I'm opening this issue as a tracking list for working through the migration. 

I will also be verifying existing `livecheck` blocks and marking old versions as `discontinued` if they have not been updated in a significant amount of time.

This will ensure things are cleaner for the eventual `homebrew-cask` repo consolidation discussed in https://github.com/Homebrew/homebrew-cask/issues/112102.

- [x] 1password-beta (Existing livecheck ✅)
- [x] 1password-cli-beta (Existing livecheck ✅)
- [x] 1password-cli1 (Existing livecheck ✅)
- [x] 1password6 #14994
- [x] 1password7 (Existing livecheck ✅)
- [x] ableton-live-intro10 #14995
- [x] ableton-live-lite10 #14996
- [x] ableton-live-standard10 #14997
- [x] ableton-live-suite10 #14998
- [x] ableton-live-suite9 #14999
- [x] adguard-nightly #15000
- [x] adguard-vpn-nightly #15001
- [x] adoptopenjdk8 (Already discontinued ✅)
- [x] aerial-beta #15002
- [x] affinity-designer-beta #15003
- [x] affinity-photo-beta #15004
- [x] affinity-publisher-beta #15005
- [x] alfred2 #15006
- [x] alfred3 #15007
- [x] alfred4 (Existing livecheck ✅)
- [x] anaconda2 #15008
- [x] android-studio-preview-beta (Existing livecheck ✅)
- [x] android-studio-preview-canary (Existing livecheck ✅)
- [x] anki-beta #15009
- [x] appcode-eap (Existing livecheck ✅)
- [x] arduino-ide-nightly (`:latest`, no reliable version info ✅)
- [x] arduino-nightly (Already discontinued ✅)
- [x] arq5 #15010
- [x] atom-beta #15011
- [x] atom-nightly #15012
- [x] azure-data-studio-insiders #15013
- [x] background-music-pre (Existing livecheck ✅)
- [x] blender-lts (Existing livecheck ✅)
- [x] brave-browser-beta (Existing livecheck ✅)
- [x] brave-browser-dev (Existing livecheck ✅)
- [x] brave-browser-nightly #15014
- [x] buckets-beta (Existing livecheck ✅)
- [x] calibre4 #15015
- [x] carbon-copy-cloner5 (Existing livecheck ✅)
- [x] charles-applejava #15016
- [ ] charles-beta (No current beta, so no available downloads to check ❌)
- [x] chromedriver-beta #15017
- [ ] citra-nightly (Not all releases are for macOS ❌)
- [x] clashx-pro (Existing livecheck ✅)
- [x] cleanmymac3 #15018
- [x] corretto11 (Existing livecheck ✅)
- [x] corretto17 (Existing livecheck ✅)
- [x] corretto8 (Existing livecheck ✅)
- [x] daedalus-flight (Existing livecheck ✅)
- [x] dash2 #15019
- [x] dash3 #15020
- [x] dash4 #15021
- [x] dash5 #15022
- [x] db-browser-for-sqlite-nightly #15023
- [x] deadbeef-nightly #15024
- [x] defold-alpha #15025
- [x] defold-beta #15026
- [x] discord-canary (Existing livecheck ✅)
- [x] discord-development (Existing livecheck ✅)
- [x] discord-ptb (Existing livecheck ✅)
- [x] docker-edge (Already discontinued ✅)
- [x] dolphin-dev (Updated frequently, URL is dynamically determined ✅)
- [x] dotnet-preview (Existing livecheck ✅)
- [x] dotnet-sdk-preview (Existing livecheck ✅)
- [x] dropbox-beta (Existing livecheck ✅)
- [x] emacs-nightly #15028
- [x] emacs-pretest (Existing livecheck ✅)
- [ ] ferdi-beta (No beta since September 2021, no reliable way to check ❌)
- [x] figma-beta (Existing livecheck ✅)
- [x] firefox-beta (Updated frequently, URL is dynamically determined ✅)
- [x] firefox-developer-edition (Updated frequently, URL is dynamically determined ✅)
- [x] firefox-esr (Existing livecheck ✅)
- [x] firefox-nightly (Updated frequently, URL is dynamically determined ✅)
- [x] forklift2 #15029
- [ ] freecad-pre (Release structure is confusing, will revisit ❌)
- [x] geogebra5 (Existing livecheck ✅)
- [x] github-beta (Existing livecheck ✅)
- [x] google-chrome-beta (Existing livecheck ✅)
- [x] google-chrome-canary (Existing livecheck ✅)
- [x] google-chrome-dev (Existing livecheck ✅)
- [x] google-japanese-ime-dev (`:latest`, no reliable version info ✅)
- [x] gpg-suite-nightly #15030
- [x] hamsket-nightly #15031
- [x] hancom-word-2014 #15032
- [x] hyper-canary (Existing livecheck ✅)
- [x] inso-beta (Existing livecheck ✅)
- [x] insomnia-alpha (Existing livecheck ✅)
- [x] intellij-idea-ce19 #15033
- [x] intellij-idea19 #15034
- [x] istat-menus5 (Existing livecheck ✅)
- [x] iterm2-beta (Existing livecheck ✅)
- [x] iterm2-legacy #15037
- [x] iterm2-nightly #15038
- [x] java-beta #15039
- [x] java6 (Already discontinued ✅)
- [x] julia-lts (Existing livecheck ✅)
- [x] julia-nightly #15040
- [x] kaleidoscope2 (Existing livecheck ✅)
- [ ] keepassxc-beta (No beta with binaries since June 2020, no reliable way to check ❌)
- [x] keepassxc-snapshot (Updated frequently, URL is dynamically determined ✅)
- [x] keka-beta (Existing livecheck ✅)
- [x] keyboard-maestro8 #15041
- [x] kitty-nightly (`:latest`, no reliable version info ✅)
- [x] ksdiff2 (Existing livecheck ✅)
- [x] lando-edge #15048
- [x] libreoffice-still (Existing livecheck ✅)
- [x] lilypond-dev #15049
- [x] little-snitch4 (Existing livecheck ✅)
- [x] local-beta (Existing livecheck ✅)
- [x] macfuse-dev #15051 
- [x] macloggerdx-beta (Existing livecheck ✅)
- [x] macpass-dev (`:latest`, no reliable version info ✅)
- [x] mailmate-beta (Existing livecheck ✅)
- [x] mi-beta (Existing livecheck ✅)
- [x] microsoft-edge-beta (Existing livecheck ✅)
- [x] microsoft-edge-dev (Existing livecheck ✅)
- [x] microsoft-office-2011 #15065
- [x] microsoft-office-2016 #15066
- [x] microsoft-openjdk11 (Existing livecheck ✅)
- [x] miniconda2 #15067
- [x] mongodb-compass-beta #15068
- [x] mono-mdk-for-visual-studio (Existing livecheck ✅)
- [x] morpheus-beta (Existing livecheck ✅)
- [x] mullvadvpn-beta (Existing livecheck ✅)
- [x] mumble-snapshot (Existing livecheck ✅)
- [x] navicat-premium15 (Existing livecheck ✅)
- [x] netnewswire-beta (Existing livecheck ✅)
- [x] obs-beta (Existing livecheck ✅)
- [x] olympus #15339 
- [x] omegat-latest (Existing livecheck ✅)
- [x] omnifocus2 #15210
- [x] omnigraffle6 #15211
- [x] omniplan3 #15212
- [x] openemu-experimental (Existing livecheck ✅)
- [x] openscad-snapshot #15340
- [x] openshot-video-editor-daily (Existing livecheck ✅)
- [x] openzfs-dev #15341
- [x] opera-beta (Existing livecheck ✅)
- [x] opera-crypto-developer (Existing livecheck ✅)
- [x] opera-developer (Existing livecheck ✅)
- [x] papers3 #15342
- [x] parallels12 (Existing livecheck ✅)
- [x] parallels13 (Existing livecheck ✅)
- [x] parallels14 (Existing livecheck ✅)
- [x] parallels15 (Existing livecheck ✅)
- [x] parallels16 (Existing livecheck ✅)
- [x] parallels17 (Existing livecheck ✅)
- [x] pdf-expert-beta (Existing livecheck ✅)
- [x] pgadmin3 #15344
- [x] picoscope-beta #15346
- [x] powershell-preview (Existing livecheck ✅)
- [x] powershell6 (Already discontinued ✅)
- [x] processing2 (Already discontinued ✅)
- [x] processing3 (Existing livecheck ✅)
- [x] propresenter-beta (Existing livecheck ✅)
- [x] propresenter6 #15347
- [x] qgis-ltr (Existing livecheck ✅)
- [x] qt-creator-dev (Existing livecheck ✅)
- [x] quicktime-player7 #15348
- [x] rambox-ce (Already discontinued ✅)
- [x] reflector2 (Existing livecheck ✅)
- [x] royal-tsx-beta (Existing livecheck ✅)
- [x] rstudio-daily (`:latest`, no reliable version info ✅)
- [x] rstudio-preview-electron (Existing livecheck ✅)
- [x] rstudio-preview (Existing livecheck ✅)
- [x] safari-technology-preview (Existing livecheck ✅)
- [x] screenflow5 #15349
- [x] semeru-jdk11-open (Existing livecheck ✅)
- [x] semeru-jdk17-open (Existing livecheck ✅)
- [x] semeru-jdk8-open (Existing livecheck ✅)
- [x] sequel-pro-nightly (`:latest`, no reliable version info ✅)
- [x] shadow-beta #15350
- [x] signal-beta (Existing livecheck ✅)
- [x] sketch-beta (Existing livecheck ✅)
- [x] skype-preview (Existing livecheck ✅)
- [x] skype7 #15351
- [x] slack-beta (Existing livecheck ✅)
- [x] slicer-preview (`:latest`, no reliable version info ✅)
- [x] smcfancontrol-beta #15352
- [x] snagit4 #15353
- [x] sonarr-beta #15354
- [x] sonos-s1-controller (Existing livecheck ✅)
- [x] soulver2 #15355
- [x] sourcetree-beta (Existing livecheck ✅)
- [x] sublime-merge-dev (Existing livecheck ✅)
- [x] sublime-text-dev (Existing livecheck ✅)
- [x] sublime-text2 #15356
- [ ] synergy-beta (development on current versions halted - https://symless.com/synergy-blog/putting-ux-first - may be an option when v3 is in beta)
- [x] telegram-desktop-beta (Existing livecheck ✅)
- [x] temurin11 (Existing livecheck ✅)
- [x] temurin17 (Existing livecheck ✅)
- [x] temurin18 #15373
- [x] temurin8 (Existing livecheck ✅)
- [x] termius-beta (Existing livecheck ✅)
- [x] textmate-preview #15374
- [x] thunderbird-beta (Updated frequently, URL is dynamically determined ✅)
- [x] thunderbird-daily (Updated frequently, URL is dynamically determined ✅)
- [x] tinymediamanager3 (Existing livecheck ✅)
- [x] tor-browser-alpha (Existing livecheck ✅)
- [x] tower2 #15375
- [x] transmission-nightly (Updated frequently, URL is dynamically determined ✅)
- [x] transmit4 (Already discontinued ✅)
- [x] tunnelblick-beta (Existing livecheck ✅)
- [x] utm-beta (Existing livecheck ✅)
- [x] virtualbox-beta (Existing livecheck for x86_64, known issue for arm64. Comments are in the cask file)
- [x] virtualbox-extension-pack-beta #15376
- [x] virtualbox6 (Existing livecheck ✅)
- [x] visual-studio-code-insiders (Updated frequently, URL is dynamically determined ✅)
- [x] vivaldi-snapshot (Existing livecheck ✅)
- [x] vlc-nightly (Updated frequently, URL is dynamically determined ✅)
- [x] vmware-fusion-tech-preview (Existing livecheck ✅)
- [x] vmware-fusion10 #15377
- [x] vmware-fusion11 #15378
- [x] vmware-fusion7 #15379
- [x] vmware-fusion8 #15380
- [x] vox2 #15381
- [x] vscodium-insiders (Existing livecheck ✅)
- [x] whatsapp-beta (Existing livecheck ✅)
- [x] whoozle-android-file-transfer-nightly (Updated frequently, URL is dynamically determined ✅)
- [x] wine-devel (Existing livecheck ✅)
- [x] wine-staging (Existing livecheck ✅)
- [x] xampp7 (Existing livecheck ✅)
- [x] xmind8 (Already discontinued ✅)
- [x] yubico-authenticator-beta (Existing livecheck ✅)
- [x] zulu11 (Existing livecheck ✅)
- [x] zulu13 (Existing livecheck ✅)
- [x] zulu15 (Existing livecheck ✅)
- [x] zulu17 (Existing livecheck ✅)
- [x] zulu7 #15382
- [x] zulu8 (Existing livecheck ✅)
