### ISSUE TITLE
Tracking issue for migrating casks to homebrew/cask

### ISSUE THREAD

**Issue by cho-m** [Homebrew/homebrew-cask-versions#19665]
This is a tracking issue for migrating casks to homebrew/cask. If a specific task requires further discussion then we can split it off into its own issue.

- [ ] Versioned cask naming convention
  - [x] Decide on scheme. Sounds like `name@(version|channel)` had no disagreement at https://github.com/Homebrew/homebrew-cask/issues/112102#issuecomment-1823781401
  - [x] Update blocking audit for `@` token - https://github.com/Homebrew/brew/pull/16865
  - [ ] Non-blocking audit updates for token - https://github.com/Homebrew/brew/pull/16882
- [x] Migration approach
  - [x] Decide on approach. Options mentioned include:
    1. **Use tap_migration in `homebrew/cask-versions` to migrate and rename in one step (advantage: cleaner on `homebrew/cask` side?)**
    2. ~~Use tap_migration in `homebrew/cask-versions` to migrate and use cask_renames in `homebrew/cask` to rename (advantage: may allow rename to work even if this repo is untapped)~~
  - [x] Check no issues via common user scenarios, e.g.
    - [x] JSON API migration
    - [x] Non-API migration and handling around untapped `homebrew/cask`.
    - [x] Maybe `auto_updates true` Casks?
- [ ] Migration with criteria (e.g. non-deprecate/disabled with either sufficient install count or maintainer usage)
    <details>
    <summary><b>Analytics as of 2024-03-13 from <a href="https://formulae.brew.sh/analytics/cask-install/365d/">Cask Install Events (365 days)</a></b></summary>
    
    | Cask | Installs | Rank | Deprecated? |
    | --- | --: | --: | --- |
    | zulu11 | 76361 | 23 |  |
    | zulu17 | 36721 | 65 |  |
    | temurin17 | 33398 | 71 |  |
    | adoptopenjdk8 | 25599 | 101 | 2023-12-17 |
    | temurin11 | 23294 | 116 |  |
    | temurin8 | 22398 | 121 |  |
    | zulu8 | 9420 | 209 |  |
    | wine-devel | 7114 | 275 |  |
    | firefox-developer-edition | 6508 | 302 |  |
    | wine-staging | 6002 | 339 |  |
    | corretto17 | 4066 | 448 |  |
    | mono-mdk-for-visual-studio | 3968 | 455 |  |
    | temurin21 | 3953 | 456 |  |
    | corretto11 | 3542 | 496 |  |
    | visual-studio-code-insiders | 3533 | 498 |  |
    | google-chrome-canary | 3324 | 515 |  |
    | corretto8 | 2327 | 640 |  |
    | java6 | 1943 | 733 | 2023-12-17 |
    | virtualbox-beta | 1624 | 807 |  |
    | temurin19 | 1484 | 848 |  |
    | powershell-preview | 1479 | 852 |  |
    | wezterm-nightly | 1465 | 864 |  |
    | microsoft-edge-dev | 1212 | 964 |  |
    | whatsapp-beta | 1211 | 965 |  |
    | temurin18 | 1149 | 996 | 2023-12-17 |
    | google-chrome-beta | 1113 | 1015 |  |
    | iterm2-beta | 1099 | 1023 |  |
    | google-chrome-dev | 959 | 1103 |  |
    | firefox-nightly | 867 | 1159 |  |
    | safari-technology-preview | 841 | 1181 |  |
    | microsoft-openjdk11 | 722 | 1287 |  |
    | microsoft-teams-classic | 700 | 1318 |  |
    | zulu21 | 700 | 1319 |  |
    | firefox-beta | 606 | 1403 |  |
    | microsoft-edge-beta | 570 | 1453 |  |
    | brave-browser-beta | 542 | 1495 |  |
    | firefox-esr | 517 | 1525 |  |
    | 1password-beta | 510 | 1538 |  |
    | discord-canary | 498 | 1555 |  |
    | virtualbox6 | 476 | 1598 |  |
    | temurin20 | 443 | 1664 |  |
    | microsoft-openjdk17 | 431 | 1687 |  |
    | dropbox-beta | 429 | 1694 |  |
    | oracle-jdk17 | 379 | 1800 |  |
    | zulu15 | 379 | 1804 | 2023-12-17 |
    | iterm2-nightly | 372 | 1819 |  |
    | signal-beta | 349 | 1880 |  |
    | brave-browser-nightly | 322 | 1951 |  |
    | zulu7 | 318 | 1967 | 2023-12-17 |
    | graalvm-jdk17 | 305 | 2005 |  |
    | pgadmin3 | 291 | 2051 |  |
    | utm-beta | 284 | 2074 |  |
    | slack-beta | 273 | 2115 |  |
    | qgis-ltr | 271 | 2123 |  |
    | brave-browser-dev | 266 | 2138 |  |
    | semeru-jdk17-open | 214 | 2392 |  |
    | discord-ptb | 208 | 2431 |  |
    | vscodium-insiders | 204 | 2461 |  |
    | 1password7 | 203 | 2462 |  |
    | sublime-text-dev | 193 | 2509 |  |
    | github-beta | 179 | 2571 |  |
    | opera-developer | 172 | 2621 |  |
    | dolphin-beta | 171 | 2626 |  |
    | vivaldi-snapshot | 169 | 2642 |  |
    | 1password-cli-beta | 167 | 2652 |  |
    | tunnelblick-beta | 165 | 2681 |  |
    | docker-edge | 160 | 2709 | 2023-12-17 |
    | dash6 | 155 | 2751 |  |
    | thunderbird-beta | 151 | 2794 |  |
    | semeru-jdk11-open | 150 | 2800 |  |
    | vmware-fusion-tech-preview | 145 | 2840 |  |
    | zotero-beta | 145 | 2841 |  |
    | vlc-nightly | 144 | 2849 |  |
    | android-studio-preview-canary | 141 | 2865 |  |
    | zed-preview | 138 | 2908 |  |
    | dolphin-dev | 136 | 2921 |  |
    | charles-applejava | 135 | 2929 | 2023-12-17 |
    | dotnet-sdk-preview | 134 | 2937 |  |
    | libreoffice-still | 130 | 2984 |  |
    | vmware-fusion12 | 122 | 3064 | 2023-12-17 |
    | alfred4 | 121 | 3065 |  |
    | semeru-jdk8-open | 117 | 3115 |  |
    | sonos-s1-controller | 117 | 3117 |  |
    | blender-lts | 115 | 3133 |  |
    | sublime-text2 | 115 | 3142 | 2023-12-17 |
    | libreoffice-still-language-pack | 114 | 3147 |  |
    | julia-nightly | 105 | 3252 |  |
    | playcover-community-beta | 103 | 3291 |  |
    | openemu-experimental | 101 | 3317 |  |
    | java-beta | 96 | 3390 |  |
    | zulu13 | 96 | 3396 | 2023-12-17 |
    | emacs-nightly | 93 | 3429 |  |
    | 1password6 | 90 | 3461 | 2023-12-17 |
    | android-studio-preview-beta | 90 | 3462 |  |
    | 1password-nightly | 89 | 3478 |  |
    | transmission-nightly | 89 | 3486 |  |
    | openscad-snapshot | 86 | 3523 |  |
    | figma-beta | 85 | 3531 |  |
    | qbittorrent-lt20 | 83 | 3576 |  |
    | sublime-text3 | 80 | 3631 | 2023-12-17 |
    | tsh13 | 77 | 3683 |  |
    | parallels17 | 76 | 3701 |  |
    | miniconda2 | 75 | 3717 | 2023-12-17 |
    | gimp-dev | 70 | 3803 |  |
    | deadbeef-nightly | 69 | 3822 |  |
    | emacs-pretest | 68 | 3843 |  |
    | mongodb-compass-beta | 68 | 3856 |  |
    | parallels18 | 67 | 3873 |  |
    | kitty-nightly | 65 | 3924 |  |
    | mullvadvpn-beta | 65 | 3928 |  |
    | chromedriver-beta | 64 | 3938 |  |
    | godot3 | 64 | 3947 |  |
    | kaleidoscope2 | 64 | 3950 |  |
    | tor-browser-alpha | 62 | 3998 |  |
    | obs-beta | 61 | 4016 |  |
    | anaconda2 | 60 | 4021 | 2023-12-17 |
    | xmind8 | 60 | 4055 | 2023-12-17 |
    | sketch-beta | 57 | 4115 |  |
    | sublime-merge-dev | 57 | 4117 |  |
    | microsoft-office-2016 | 51 | 4271 | 2023-12-17 |
    | discord-development | 50 | 4281 |  |
    | vox2 | 50 | 4301 | 2023-12-17 |
    | opera-beta | 49 | 4331 |  |
    | db-browser-for-sqlite-nightly | 48 | 4348 |  |
    | julia-lts | 46 | 4415 |  |
    | telegram-desktop-beta | 46 | 4427 |  |
    | macfuse-dev | 45 | 4444 |  |
    | whoozle-android-file-transfer-nightly | 45 | 4454 |  |
    | whatsapp-legacy | 43 | 4521 |  |
    | forklift3 | 41 | 4581 | 2023-12-17 |
    | keka-beta | 41 | 4585 |  |
    | skype-preview | 40 | 4636 |  |
    | dash5 | 39 | 4650 | 2023-12-17 |
    | 1password-cli1 | 36 | 4782 |  |
    | threema-beta | 36 | 4830 |  |
    | geogebra5 | 32 | 5038 |  |
    | qt-creator-dev | 32 | 5047 |  |
    | alfred3 | 31 | 5060 | 2023-12-17 |
    | azure-data-studio-insiders | 31 | 5063 |  |
    | surge4 | 30 | 5176 |  |
    | dash4 | 29 | 5189 | 2023-12-17 |
    | mailmate-beta | 29 | 5244 |  |
    | typora-dev | 28 | 5333 |  |
    | arduino-ide-nightly | 27 | 5335 |  |
    | dotnet-preview | 27 | 5343 |  |
    | istat-menus5 | 27 | 5390 |  |
    | thunderbird-daily | 27 | 5410 |  |
    | postico1 | 26 | 5503 |  |
    | sourcetree-beta | 26 | 5512 |  |
    | gpg-suite-nightly | 25 | 5612 |  |
    | hyper-canary | 24 | 5735 |  |
    | cleanmymac3 | 23 | 5763 | 2023-12-17 |
    | termius-beta | 23 | 5875 |  |
    | google-japanese-ime-dev | 22 | 6001 |  |
    | adguard-nightly | 21 | 6032 |  |
    | insomnia-alpha | 20 | 6295 |  |
    | netnewswire-beta | 20 | 6306 |  |
    | microsoft-office-2019 | 19 | 6453 | 2023-12-17 |
    | vmware-fusion11 | 19 | 6466 | 2023-12-17 |
    | affinity-designer1 | 17 | 6602 |  |
    | calibre4 | 17 | 6606 | 2023-12-17 |
    | intellij-idea-eap | 17 | 6696 |  |
    | mixxx-snapshot | 17 | 6701 |  |
    | powershell6 | 17 | 6706 | 2023-12-17 |
    | quicktime-player7 | 17 | 6707 | 2023-12-17 |
    | shadow-beta | 17 | 6714 |  |
    | kaleidoscope3 | 16 | 6825 |  |
    | keepassxc-beta | 16 | 6826 |  |
    | postmancanary | 16 | 6842 |  |
    | rstudio-daily | 16 | 6844 |  |
    | beyond-compare-beta | 15 | 6860 |  |
    | db-browser-for-sqlcipher-nightly | 15 | 6862 |  |
    | forklift2 | 14 | 7008 | 2023-12-17 |
    | intellij-idea-ce19 | 13 | 7089 | 2023-12-17 |
    | parallels16 | 13 | 7097 |  |
    | transmit4 | 13 | 7110 | 2023-12-17 |
    | vmware-fusion10 | 13 | 7114 | 2023-12-17 |
    | affinity-photo1 | 12 | 7120 |  |
    | monal-beta | 12 | 7167 |  |
    | arq5 | 11 | 7193 | 2023-12-17 |
    | dash3 | 11 | 7199 | 2023-12-17 |
    | element-nightly | 11 | 7204 |  |
    | pdf-expert-beta | 11 | 7231 |  |
    | smcfancontrol-beta | 11 | 7239 |  |
    | aerial-beta | 10 | 7252 |  |
    | affinity-publisher1 | 10 | 7253 |  |
    | firefox-cn | 10 | 7265 |  |
    | hamsket-nightly | 10 | 7278 | 2024-01-01 |
    | hancom-word-2014 | 10 | 7279 | 2023-12-17 |
    | processing3 | 10 | 7296 |  |
    | rambox-ce | 10 | 7298 | 2023-12-17 |
    | carbon-copy-cloner5 | 9 | 7327 |  |
    | opera-crypto-developer | 9 | 7369 |  |
    | dash2 | 8 | 7405 | 2023-12-17 |
    | folding-at-home-beta | 8 | 7415 |  |
    | little-snitch4 | 8 | 7444 |  |
    | slicer-preview | 8 | 7468 |  |
    | xmind-beta | 8 | 7488 |  |
    | ableton-live-suite10 | 7 | 7493 | 2023-12-17 |
    | iterm2-legacy | 7 | 7527 | 2023-12-17 |
    | royal-tsx-beta | 7 | 7552 |  |
    | xampp7 | 7 | 7577 |  |
    | atom-beta | 6 | 7585 | 2023-12-17 |
    | omnifocus2 | 6 | 7648 | 2023-12-17 |
    | openra-playtest | 6 | 7649 |  |
    | reflector2 | 6 | 7657 |  |
    | tower2 | 6 | 7680 | 2023-12-17 |
    | virtualbuddy-beta | 6 | 7688 |  |
    | ableton-live-suite11 | 5 | 7700 |  |
    | alfred2 | 5 | 7703 | 2023-12-17 |
    | omnigraffle6 | 5 | 7788 | 2023-12-17 |
    | omniplan3 | 5 | 7789 | 2023-12-17 |
    | openshot-video-editor-daily | 5 | 7792 |  |
    | soulver2 | 5 | 7813 | 2023-12-17 |
    | ableton-live-lite10 | 4 | 7836 | 2023-12-17 |
    | adguard-vpn-nightly | 4 | 7837 |  |
    | ksdiff2 | 4 | 7930 | 2023-12-17 |
    | navicat-premium15 | 4 | 7953 |  |
    | papers3 | 4 | 7969 | 2023-12-17 |
    | vmware-fusion7 | 4 | 8024 | 2023-12-17 |
    | ableton-live-intro10 | 3 | 8037 | 2023-12-17 |
    | ableton-live-suite9 | 3 | 8038 | 2023-12-17 |
    | intellij-idea19 | 3 | 8147 | 2023-12-17 |
    | local-beta | 3 | 8178 |  |
    | omegat-latest | 3 | 8208 |  |
    | parallels15 | 3 | 8215 |  |
    | vmware-fusion8 | 3 | 8287 | 2023-12-17 |
    | defold-beta | 2 | 8408 |  |
    | keepassxc-snapshot | 2 | 8563 |  |
    | olympus | 2 | 8645 |  |
    | skype7 | 2 | 8719 | 2023-12-17 |
    | sonarr-beta | 2 | 8724 |  |
    | arduino-nightly | 1 | 8913 | 2023-12-17 |
    | bbedit14 | 1 | 8945 |  |
    | daedalus-flight | 1 | 9092 |  |
    | keyboard-maestro8 | 1 | 9623 | 2023-12-17 |
    | parallels13 | 1 | 9898 |  |
    | picoscope-beta | 1 | 9919 |  |
    | processing2 | 1 | 9956 | 2023-12-17 |
    | propresenter-beta | 1 | 9960 |  |
    </details>

- [ ] Documentation
  - [ ] Update `homebrew/cask` repo templates, e.g. https://github.com/Homebrew/homebrew-cask/blob/master/.github/PULL_REQUEST_TEMPLATE.md
  - [ ] Update https://docs.brew.sh, e.g.
    - [ ] https://docs.brew.sh/Acceptable-Casks#beta-unstable-development-nightly-or-legacy
    - [ ] https://docs.brew.sh/Cask-Cookbook#simplified-names-of-apps
    - [ ] https://docs.brew.sh/Cask-Cookbook#tap-specific-cask-token-examples
    - [ ] Optional: Maybe move & update content in https://github.com/Homebrew/homebrew-cask-versions/blob/master/CONTRIBUTING.md to Cookbook
    - [ ] Optional: If we want, we could add dedicated info for Versioned Casks similar to formulae in https://docs.brew.sh/Versions 
- [ ] Close issue and archive repo

**Comment by razvanazamfirei** [comment]
Remaining:
- [ ] daedalus-flight
- [ ] macfuse-dev
- [ ] olympus
- [ ] parallels15
- [ ] rstudio-daily
- [ ] semeru-jdk11-open
- [ ] semeru-jdk17-open
- [ ] semeru-jdk8-open

Deprecated casks:
- [ ] 1password6
- [ ] ableton-live-intro10
- [ ] ableton-live-lite10
- [ ] ableton-live-standard10
- [ ] ableton-live-suite10
- [ ] ableton-live-suite9
- [ ] adoptopenjdk8
- [ ] alfred2
- [ ] alfred3
- [ ] anaconda2
- [ ] arduino-nightly
- [ ] arq5
- [ ] atom-beta
- [ ] atom-nightly
- [ ] calibre4
- [ ] charles-applejava
- [ ] cleanmymac3
- [ ] dash2
- [ ] dash3
- [ ] dash4
- [ ] dash5
- [ ] docker-edge
- [ ] forklift2
- [ ] forklift3
- [ ] hamsket-nightly
- [ ] hancom-word-2014
- [ ] intellij-idea-ce19
- [ ] intellij-idea19
- [ ] iterm2-legacy
- [ ] java6
- [ ] keyboard-maestro8
- [ ] ksdiff2
- [ ] microsoft-office-2016
- [ ] microsoft-office-2019
- [ ] miniconda2
- [ ] morpheus-beta
- [ ] omnifocus2
- [ ] omnigraffle6
- [ ] omniplan3
- [ ] papers3
- [ ] powershell6
- [ ] processing2
- [ ] propresenter6
- [ ] quicktime-player7
- [ ] rambox-ce
- [ ] skype7
- [ ] soulver2
- [ ] sublime-text2
- [ ] sublime-text3
- [ ] temurin18
- [ ] tower2
- [ ] transmit4
- [ ] vmware-fusion10
- [ ] vmware-fusion11
- [ ] vmware-fusion12
- [ ] vmware-fusion7
- [ ] vmware-fusion8
- [ ] vox2
- [ ] xmind8
- [ ] zulu13
- [ ] zulu15
- [ ] zulu7
